### ISSUE TITLE
boiler-plate를 새 repository에 적용할 경우 push 되지 않음.

### ISSUE THREAD

**Issue by jhoon9494** [Wanted-PreOnboarding-Team-8/boiler-plate#7]
## 문제 상황
- 2차 과제 레포 생성 후 boiler-plate를 push 하였으나, husky pre-push에서 중단 및 에러 발생
- origin/master 브랜치가 없는 상황에서 해당 브랜치를 호출하여 발생되는 것으로 판단됨.
<Img src="https://user-images.githubusercontent.com/82688516/223366735-d6e14c49-0f10-4101-b1b8-96e450a15ebc.png" alt="bug-image-1" width=500 />

**Comment by greyHairChooseLife** [comment]
<br>
먼저 PR에 앞서 테스트가 미흡했던 점 죄송합니다. boiler-plate를 클론 받아서 시작하는 경우를 생각하지 못헀습니다.

## 문제 상황 재현: 

1. boiler-plate 레포 클론
2. 개인 원격 저장소 새로 만들고,  `git remote add origin {github_repo_url}`으로 클론 받은 로컬 저장소와 연결
3. `npm install` 이후 2에서 연결 한 개인 원격 저장소에 최초의 `git-push`를 날리면 문제 발생

## 문제 원인:

정훈님이 말씀하신 것이 정확합니다.
```
(.husky/pre-push 41~47 번 라인)
(가독성을 위해 필요 없는 부분을 제거했습니다.)

git log --oneline origin/master...HEAD > changedList.txt
git diff --name-only origin/master...HEAD >> changedList.txt
```
위 두 라인은 origin/master 브랜치부터 HEAD 브랜치까지의 커밋 내역과 파일 변경 내역을 조회합니다.

__하지만 `git clone`으로 새롭게 생성한 로컬 저장소에는 오로지 master(즉 HEAD) 밖에 존재하지 않습니다. 존재하지 않는 origin/master 브랜치를 참조하려 했기 때문에 이 같은 오류가 발생했습니다.__

## 해결:

origin/master 브랜치가 아직 존재하지 않는 경우를 커버 할 수 있도록 간단히 업데이트하여 PR올리도록 하겠습니다.

## 관련 주의 사항:

위와 같은 문제는 오로지 클론 받아서 최초 `git push`를 진행 할 때만 발생합니다. `git push` 한다는 것은 `git remote`에 자신의 원격 저장소가 연결되어 있다는 뜻이고, 그렇다면 origin/master 브랜치는 반드시 존재하기 때문입니다.

__단, 자신의 원격 저장소에 default 브랜치 이름을 기본값(master)으로 유지 해 주셔야합니다. main 등으로 바꾼다거나, 브랜치 관리를 따로 하지 않고 master브랜치로 추가 개발 및 PR을 날리신다면 에러가 발생합니다.__

혹시 이 부분 납득 가지 않으신다면 코멘트나 디코로 메시지 바랍니다!
